import { notFound } from 'next/navigation';
import { getSummaryByToken } from '@/lib/db';
import SummaryCard from '@/components/SummaryCard';
import ActionItemsTable from '@/components/ActionItemsTable';
import type { Metadata } from 'next';

interface Props {
  params: Promise<{ token: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { token } = await params;
  const data = await getSummaryByToken(token);
  if (!data) return { title: 'Meeting Not Found — MeetMind' };
  return {
    title: `${data.meeting.title} — MeetMind`,
    description: data.summary.overview,
  };
}

export default async function SharePage({ params }: Props) {
  const { token } = await params;
  const data = await getSummaryByToken(token);

  if (!data) notFound();

  const { summary, meeting, action_items } = data;

  const formatDate = (iso: string) =>
    new Date(iso).toLocaleDateString('en-US', {
      weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
    });

  return (
    <main>
      <div className="container">
        <div className="page-header">
          {/* Shared banner */}
          <div
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 6,
              background: 'var(--accent-glow)',
              border: '1px solid var(--accent-border)',
              borderRadius: 99,
              padding: '4px 14px',
              fontSize: '0.75rem',
              color: 'var(--accent-light)',
              marginBottom: 16,
            }}
          >
            🔗 Shared Meeting Summary
          </div>

          <h1 className="page-title" style={{ fontSize: '1.6rem' }}>{meeting.title}</h1>
          <p className="page-subtitle">{formatDate(meeting.created_at)}</p>
        </div>

        {/* Summary */}
        <section className="card mb-6">
          <p className="section-title mb-4">📋 Meeting Summary</p>
          <SummaryCard summary={summary} />
        </section>

        {/* Action Items (read-only) */}
        <section className="card mb-6">
          <p className="section-title mb-4">✅ Action Items ({action_items.length})</p>
          <ActionItemsTable items={action_items} meetingId={meeting.id} readOnly />
        </section>

        {/* Footer */}
        <div style={{ textAlign: 'center', padding: '32px 0', color: 'var(--text-muted)', fontSize: '0.8rem' }}>
          Generated by{' '}
          <a href="/" style={{ color: 'var(--accent-light)', textDecoration: 'none' }}>
            MeetMind
          </a>
          {' '}· Powered by Groq Whisper + Gemini 1.5 Flash
        </div>
      </div>
    </main>
  );
}
